name: Build & Publish (Porkbun Static Hosting)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: porkbun-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Detect package manager
      - name: Detect package manager
        id: pm
        run: |
          if [ -f pnpm-lock.yaml ]; then echo "manager=pnpm" >> $GITHUB_OUTPUT;
          elif [ -f yarn.lock ]; then echo "manager=yarn" >> $GITHUB_OUTPUT;
          else echo "manager=npm" >> $GITHUB_OUTPUT; fi

      - name: Enable corepack (for yarn/pnpm)
        if: steps.pm.outputs.manager != 'npm'
        run: corepack enable

      - name: Install deps
        run: |
          case "${{ steps.pm.outputs.manager }}" in
            pnpm) pnpm install --frozen-lockfile ;;
            yarn) yarn install --frozen-lockfile ;;
            npm)  (npm ci || npm i) ;;
          esac

      - name: Build
        run: |
          case "${{ steps.pm.outputs.manager }}" in
            pnpm) pnpm run build ;;
            yarn) yarn build ;;
            npm)  npm run build ;;
          esac

      - name: Prepare output folder
        run: |
          if [ -d "dist" ]; then OUT="dist";
          elif [ -d "build" ]; then OUT="build";
          else echo "No build output found (dist/ or build/)"; exit 1; fi
          mv "$OUT" out

      - name: Publish to deploy branch
        run: |
          cd out
          git init
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Deploy $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git branch -M deploy
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push -f origin deploy
