name: Build & Publish (Porkbun Static Hosting)

on:
  push:
    branches: [ main ]   # build on pushes to main
  workflow_dispatch:      # allow manual runs

permissions:
  contents: write

concurrency:
  group: porkbun-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Detect Vite (dist) vs CRA (build) output folder
      - name: Prepare output folder
        run: |
          if [ -d "dist" ]; then OUT="dist";
          elif [ -d "build" ]; then OUT="build";
          else echo "No build output found (dist/ or build/)"; exit 1; fi
          mv "$OUT" out

      # Publish compiled files to the deploy branch
      - name: Publish to deploy branch
        run: |
          cd out
          git init
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Deploy $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git branch -M deploy
          git remote add origin "https://github.com/${{ github.repository }}.git"
          git push -f origin deploy

